import type { CliCommand } from "./commands.js";

export type CliCommandName =
	| "health"
	| "login"
	| "register"
	| "revoke-token"
	| "rotate-token"
	| "me"
	| "homes"
	| "memberships"
	| "summary"
	| "backup-export"
	| "bulk-preview"
	| "bulk-apply"
	| "notification-integrations"
	| "set-email-notification"
	| "delete-notification-integration"
	| "reminder-deliveries"
	| "task-reminder-schedule"
	| "set-task-reminder-schedule"
	| "delete-task-reminder-schedule"
	| "templates"
	| "template"
	| "recommendations"
	| "instantiate-template"
	| "complete-task"
	| "assets"
	| "create-asset"
	| "asset"
	| "update-asset"
	| "archive-asset"
	| "tasks"
	| "create-task"
	| "task"
	| "update-task"
	| "task-completions"
	| "archive-task"
	| "skill";

export const cliCommandName = (command: CliCommand): CliCommandName => {
	switch (command.kind) {
		case "revoke_token":
			return "revoke-token";
		case "rotate_token":
			return "rotate-token";
		case "backup_export":
			return "backup-export";
		case "bulk_preview":
			return "bulk-preview";
		case "bulk_apply":
			return "bulk-apply";
		case "notification_integrations":
			return "notification-integrations";
		case "set_email_notification":
			return "set-email-notification";
		case "delete_notification_integration":
			return "delete-notification-integration";
		case "task_reminder_schedule":
			return "task-reminder-schedule";
		case "set_task_reminder_schedule":
			return "set-task-reminder-schedule";
		case "delete_task_reminder_schedule":
			return "delete-task-reminder-schedule";
		case "reminder_deliveries":
			return "reminder-deliveries";
		case "instantiate_template":
			return "instantiate-template";
		case "complete_task":
			return "complete-task";
		case "create_asset":
			return "create-asset";
		case "update_asset":
			return "update-asset";
		case "archive_asset":
			return "archive-asset";
		case "create_task":
			return "create-task";
		case "update_task":
			return "update-task";
		case "task_completions":
			return "task-completions";
		case "archive_task":
			return "archive-task";
		case "skill_list":
		case "skill":
			return "skill";
		case "health":
		case "login":
		case "register":
		case "me":
		case "homes":
		case "memberships":
		case "summary":
		case "templates":
		case "template":
		case "recommendations":
		case "assets":
		case "asset":
		case "tasks":
		case "task":
			return command.kind;
	}
};
